# dynamixel goal velocity
DYNAMIXEL_GOAL_VELOCITY_: 5

# hsv param: hand
H_MIN_HAND_:  90
H_MAX_HAND_: 150
S_MIN_HAND_:  50
S_MAX_HAND_: 255
V_MIN_HAND_:  50
V_MAX_HAND_: 255

# dobot current position
DOBOT_X_: 318.0
DOBOT_Y_: -7.7
DOBOT_Z_: -18.3
DOBOT_R_: -31.4

# deformation
DEFORMATION_TH_: 50

# deformation
OCCLUSION_TH_: 150